data:
  src: gloss
  trg: skels
  files: files
  train: ./Data/P2014T_Ben/train
  dev: ./Data/P2014T_Ben/dev
  test: ./Data/P2014T_Ben/test
  max_sent_length: 300
  skip_frames: 1
  src_vocab: ./Configs/src_vocab.txt

training:
  # ---- keep everything as-is (your PINN config) ----
  overwrite: false
  save_model: true
  random_seed: 27
  optimizer: adam
  learning_rate: 0.001
  learning_rate_min: 0.0002
  weight_decay: 0.0
  clip_grad_norm: 5.0
  batch_size: 64
  scheduling: plateau
  patience: 7
  decrease_factor: 0.7
  early_stopping_metric: dtw
  epochs: 20000
  validation_freq: 2000
  logging_freq: 250
  eval_metric: dtw

  # ---- checkpoint saving behavior SAME AS the "Base" YAML ----
  # (Base uses: model_dir, overwrite, continue, keep_last_ckpts)
  model_dir: /home/user2/THESIS/Sign-IDD-main/Models/PINN_scratch_run1
  overwrite: false
  continue: true
  keep_last_ckpts: 1

  # ---- rest of your training config (unchanged) ----
  shuffle: true
  use_cuda: true
  max_output_length: 300
  loss: L1
  bone_loss: MSE
  hand_joint_weight: 1.5
  body_joint_weight: 1.0
  body_bonelen_weight: 0.05
  hand_bonelen_weight: 0.05
  lambda_bone: 0.1

  # ---------------- PINN (NEW) ----------------
  use_pinn: true
  pinn_weight: 0.1

  pinn_lambda_bone: 1.0
  pinn_lambda_vel: 0.1
  pinn_lambda_acc: 0.05
  pinn_lambda_fk: 0.5

  pinn_dt: 1.0
  pinn_rest_from: first_valid
  pinn_detach_rest: true
  pinn_use_huber: true
  pinn_huber_delta: 1.0

model:
  encoder:
    type: transformer
    embeddings:
      embedding_dim: 512
      dropout: 0.1
    hidden_size: 512
    ff_size: 2048
    num_layers: 6
    num_heads: 8
    dropout: 0.1

  trg_size: 150

  diffusion:
    timesteps: 100
    sampling_timesteps: 100
